version: "3"
services:
  web:
    image: namgivu/friendlyhello:1.0 #MUST matched with value defined by $IMAGE_NAME_REMOTE @ s00_config.sh

    deploy:
      #run five instances of the image we uploaded in step 2 as a service called `web`, limiting each one to use, at most, 10% of the CPU (across all cores), and 50MB of RAM.
      replicas: 5
      resources:
        limits:
          cpus: "0.1"
          memory: 50M

      #immediately restart containers if one fails
      restart_policy:
        condition: on-failure

    #map a port on the run-host to the container’s exposed-port
    ports:
      - "5000:80" #MUST matched with value defined by $R_PORT:$E_PORT @ s00_config.sh

    #instruct web’s containers to share port 80 via a load-balanced network called `webnet`
    networks:
      - webnet

#define the `webnet` network with the default settings (which is a load-balanced overlay network)
networks:
  webnet:
